name:                notewell
version:             0.2.0.0
github:              "ix/notewell"
license:             BSD3
author:              "Rose"
maintainer:          "rose@empty.town"
copyright:           "Rose 2019"

extra-source-files:
- README.md
- ChangeLog.md

data-dir: .
data-files: 
  - themes/**/*.css
  - themes/**/*.svg

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ix/notewell#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.3 && < 1.3
- gi-gtk >= 3.0.31 && < 3.1
- gi-gtk-declarative >= 0.6.0 && < 0.7
- gi-gtk-declarative-app-simple >= 0.6.0 && < 0.7
- cmark-gfm >= 0.2.0 && < 0.3
- gi-gdkpixbuf >= 2.0.23 && < 2.1
- gi-gdk >= 3.0.21 && < 3.1
- haskell-gi-base >= 0.23.0 && < 0.24
- gi-glib
- gi-pango >= 1.0.21 && < 1.1
- transformers >= 0.5.6 && < 0.6
- async >= 2.2.2 && < 2.3
- vector >= 0.12.0 && < 0.13
- bytestring >= 0.10.8 && < 0.11

library:
  source-dirs: src
  other-modules:
    - Paths_notewell

executables:
  notewell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notewell
    other-modules:
    - Paths_notewell

tests:
  notewell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notewell
