name:                notewell
version:             1.0.2.0
github:              "ix/notewell"
license:             BSD3
author:              "Rose"
maintainer:          "rose@empty.town"
copyright:           "Rose 2019"

extra-source-files:
- README.md
- ChangeLog.md

data-dir: .
data-files: 
  - themes/*.json
  - themes/**/*.svg

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ix/notewell#readme>

dependencies:
- aeson                         >= 1.4.5 && < 1.5
- base                          >= 4.12.0 && < 4.13
- bytestring                    >= 0.10.8 && < 0.11
- text                          >= 1.2.3 && < 1.3
- transformers                  >= 0.5.6 && < 0.6
- vector                        >= 0.12.0 && < 0.13
- async                         >= 2.2.2 && < 2.3
- cmark-gfm                     >= 0.2.0 && < 0.3
- filepath                      >= 1.4.2 && < 1.5
- gi-gdk                        >= 3.0.22 && < 3.1
- haskell-gi-base               >= 0.23.0 && < 0.24
- gi-gdkpixbuf                  >= 2.0.23 && < 2.1
- gi-glib                       >= 2.0.23 && < 2.1
- gi-gobject                    >= 2.0.22 && < 2.1
- gi-pango                      >= 1.0.22 && < 1.1
- gi-gtk                        >= 3.0.32 && < 3.1
- gi-gtk-declarative            >= 0.6.0 && < 0.7
- gi-gtk-declarative-app-simple >= 0.6.0 && < 0.7
- shakespeare                   >= 2.0.22 && < 2.1

library:
  source-dirs: src
  other-modules:
    - Paths_notewell

executables:
  notewell:
    main:                Main.hs
    source-dirs:         app
    when:
      - condition: 'os(windows)'
        then:
          ghc-options:  
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          - -optl-mwindows
          - -O2
        else:
          ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          - -O2
    dependencies:
    - notewell
    other-modules:
    - Paths_notewell

tests:
  notewell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notewell
