name:                bene
version:             0.1.0.0
github:              "ix/bene"
license:             BSD3
author:              "Rose"
maintainer:          "rose@empty.town"
copyright:           "Rose 2019"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- themes/giorno/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ix/bene#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.3 && < 1.3
- gi-gtk >= 3.0.31 && < 3.1
- gi-gtk-declarative >= 0.5 && < 0.6
- gi-gtk-declarative-app-simple >= 0.5 && < 0.6
- cmark-gfm >= 0.2.0 && < 0.3
- gi-gdk >= 3.0.21 && < 3.1
- async >= 2.2.2 && < 2.3
- bytestring >= 0.10.8 && < 0.11

library:
  source-dirs: src

executables:
  bene:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bene

tests:
  bene-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bene
